export const COMBAT_UNARMED = "COMBAT_UNARMED";
export const COMBAT_2H_WEAPON = "COMBAT_2H_WEAPON";
export const COMBAT_1H_WEAPON = "COMBAT_1H_WEAPON";
export const COMBAT_DUAL_1H_WEAPON = "COMBAT_DUAL_1H_WEAPON";
export const CRAFTING_BLACKSMITH = "CRAFTING_BLACKSMITH";
export const CRAFTING_ALCHEMY = "CRAFTING_ALCHEMY";
export const CRAFTING_COOKING = "CRAFTING_COOKING";
export const LEARNING_LAW = "LEARNING_LAW";
export const LEARNING_GUTTER = "LEARNING_GUTTER";
export const LEARNING_HISTORY = "LEARNING_HISTORY";
export const LEARNING_CULTURE = "LEARNING_CULTURE";


export function allSkillTypes() {
    return [
        COMBAT_UNARMED,
        COMBAT_2H_WEAPON,
        COMBAT_1H_WEAPON,
        COMBAT_DUAL_1H_WEAPON,
        CRAFTING_BLACKSMITH,
        CRAFTING_ALCHEMY,
        CRAFTING_COOKING,
        LEARNING_LAW,
        LEARNING_GUTTER,
        LEARNING_HISTORY,
        LEARNING_CULTURE,
    ];
}